slack:
  save:
    messages: false
    events: false
    commands: false
    actions: false
  refresh:
    user: 3600
    channel: 3600
    group: 3600
  endpoints:
    commands: false
    actions: false
    events: false
  plugins:
    - sirbot.slack.example
